# Generated by Django 3.2.9 on 2021-11-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date_time_sub',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date submitted'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date_time_voted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date fully voted'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
