# Generated by Django 3.2.9 on 2021-12-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0003_auto_20211127_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincetonSub',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='secport.submission')),
            ],
            bases=('secport.submission',),
        ),
        migrations.CreateModel(
            name='TestSub',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='secport.submission')),
            ],
            bases=('secport.submission',),
        ),
    ]
