# Generated by Django 3.2.9 on 2021-12-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0004_princetonsub_testsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='princetonsub',
            name='pton',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='testsub',
            name='test',
            field=models.IntegerField(default=7),
        ),
    ]
