# Generated by Django 3.2.9 on 2021-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0006_auto_20211224_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSubmission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=10000)),
                ('type', models.CharField(max_length=20)),
                ('rep_secret', models.CharField(max_length=30)),
                ('oks', models.IntegerField(default=0)),
                ('not_oks', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('dt_sub', models.DateTimeField(blank=True, null=True, verbose_name='date submitted')),
                ('dt_decided', models.DateTimeField(blank=True, null=True, verbose_name='date fully voted')),
            ],
        ),
        #migrations.RemoveField(
        #    model_name='testsub',
        #    name='submission_ptr',
        #),
        migrations.AddField(
            model_name='comment',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='conf_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='dt_decided',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date fully voted'),
        ),
        migrations.AddField(
            model_name='submission',
            name='dt_sub',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date submitted'),
        ),
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.CharField(default='unspec', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='not_oks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='oks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='rep_secret',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.CharField(default='unspec', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PrincetonSub',
        ),
        migrations.DeleteModel(
            name='TestSub',
        ),
    ]
