# Generated by Django 3.2.9 on 2021-12-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0007_auto_20211225_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='conf_num',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='group',
        ),
    ]
