# Generated by Django 3.2.9 on 2021-12-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0008_auto_20211225_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='conf_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.CharField(default='unspec', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
