# Generated by Django 3.2.9 on 2021-12-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0009_auto_20211225_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupSubmission',
        ),
    ]
