# Generated by Django 3.2.9 on 2021-12-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0010_delete_backupsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='conf_num',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='group',
        ),
    ]
