# Generated by Django 3.2.9 on 2021-12-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0011_auto_20211227_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
