# Generated by Django 3.2.9 on 2021-12-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secport', '0012_auto_20211227_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group', models.CharField(default='unspec', max_length=20)),
                ('type', models.CharField(default='unspec', max_length=20)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('rep_secret', models.CharField(blank=True, max_length=30, null=True)),
                ('yays', models.IntegerField(default=0)),
                ('nays', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('conf_num', models.IntegerField(blank=True, null=True)),
                ('dt_sub', models.DateTimeField(blank=True, null=True, verbose_name='when submitted')),
                ('dt_decided', models.DateTimeField(blank=True, null=True, verbose_name='when fully voted')),
                ('dt_published', models.DateTimeField(blank=True, null=True, verbose_name='when published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comment_num', models.IntegerField(default=0)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secport.submission')),
            ],
        ),
    ]
