# Generated by Django 3.2.9 on 2021-12-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0013_comment_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('facebook', models.IntegerField(default=0)),
                ('instagram', models.IntegerField(default=0)),
                ('twitter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RepSecret',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_used', models.DateTimeField(verbose_name='when first used')),
                ('last_used', models.DateTimeField(verbose_name='when last used')),
                ('rep_score', models.FloatField(default=1.0)),
                ('acc_yays', models.IntegerField(default=0)),
                ('acc_nays', models.IntegerField(default=0)),
                ('inacc_yays', models.IntegerField(default=0)),
                ('inacc_nays', models.IntegerField(default=0)),
            ],
        ),
    ]
