# Generated by Django 3.2.9 on 2021-12-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0015_submission_cw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rep_secret', models.CharField(max_length=20)),
                ('mod_id', models.CharField(max_length=50)),
                ('yay', models.BooleanField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('cw', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
