# Generated by Django 3.2.9 on 2021-12-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0016_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
    ]
