# Generated by Django 3.2.9 on 2021-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0017_auto_20211229_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='next_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moderation',
            name='group',
            field=models.CharField(default='unspec', max_length=20),
        ),
        migrations.AddField(
            model_name='repsecret',
            name='group',
            field=models.CharField(default='unspec', max_length=20),
        ),
    ]
