# Generated by Django 3.2.9 on 2021-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0020_alter_submission_cw'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='num_coms',
            field=models.IntegerField(default=0),
        ),
    ]
