# Generated by Django 3.2.9 on 2021-12-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0021_submission_num_coms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderation',
            old_name='mod_id',
            new_name='sub_id',
        ),
        migrations.AddField(
            model_name='repsecret',
            name='subs',
            field=models.IntegerField(default=0),
        ),
    ]
