# Generated by Django 3.2.9 on 2021-12-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0022_auto_20211230_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repsecret',
            old_name='subs',
            new_name='num_subs',
        ),
    ]
