# Generated by Django 3.2.9 on 2021-12-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0023_rename_subs_repsecret_num_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='confession',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Moderation',
        ),
        migrations.DeleteModel(
            name='RepSecret',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
