# Generated by Django 3.2.9 on 2021-12-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secport', '0024_auto_20211230_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('next_num', models.IntegerField(default=1)),
                ('facebook', models.BooleanField(default=False)),
                ('instagram', models.BooleanField(default=False)),
                ('twitter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group', models.CharField(default='unspec', max_length=20)),
                ('rep_secret', models.CharField(max_length=20)),
                ('sub_id', models.CharField(max_length=50)),
                ('yay', models.BooleanField(blank=True, null=True)),
                ('quality', models.FloatField(default=0.0)),
                ('cw', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepSecret',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('group', models.CharField(default='unspec', max_length=20)),
                ('first_used', models.DateTimeField(verbose_name='when first used')),
                ('last_used', models.DateTimeField(verbose_name='when last used')),
                ('rep_score', models.FloatField(default=1.0)),
                ('num_subs', models.IntegerField(default=0)),
                ('acc_yays', models.IntegerField(default=0)),
                ('acc_nays', models.IntegerField(default=0)),
                ('inacc_yays', models.IntegerField(default=0)),
                ('inacc_nays', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group', models.CharField(default='unspec', max_length=20)),
                ('type', models.CharField(default='unspec', max_length=20)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('rep_secret', models.CharField(blank=True, max_length=30, null=True)),
                ('yays', models.IntegerField(default=0)),
                ('nays', models.IntegerField(default=0)),
                ('quality', models.FloatField(default=0.0)),
                ('cw', models.CharField(default='{}', max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('conf_num', models.IntegerField(blank=True, null=True)),
                ('num_coms', models.IntegerField(default=0)),
                ('dt_sub', models.DateTimeField(blank=True, null=True, verbose_name='when submitted')),
                ('dt_decided', models.DateTimeField(blank=True, null=True, verbose_name='when fully voted')),
                ('dt_published', models.DateTimeField(blank=True, null=True, verbose_name='when published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comment_num', models.IntegerField(default=0)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secport.submission')),
            ],
        ),
    ]
