# Generated by Django 3.2.9 on 2021-12-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0025_comment_group_moderation_repsecret_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='repsecret',
            name='num_mods',
            field=models.IntegerField(default=0),
        ),
    ]
