# Generated by Django 3.2.9 on 2022-01-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0026_repsecret_num_mods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='group',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='group',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='conf_num',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='type',
        ),
        migrations.AddField(
            model_name='group',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='ig_user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='timezone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='dt_last_mod',
            field=models.DateTimeField(blank=True, null=True, verbose_name='when last modded'),
        ),
        migrations.AddField(
            model_name='submission',
            name='fb_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ig_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='parent_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='sub_num',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='group',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
