# Generated by Django 3.2.9 on 2022-01-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0027_auto_20220111_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='fb_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ig_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
