# Generated by Django 3.2.9 on 2022-01-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0032_alter_postimage_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AddField(
            model_name='group',
            name='avg_delay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='group',
            name='fb_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='ig_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
