# Generated by Django 3.2.9 on 2022-01-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0033_auto_20220122_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Moderation',
        ),
        migrations.DeleteModel(
            name='RepSecret',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
