# Generated by Django 3.2.9 on 2022-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secport', '0034_auto_20220122_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('timezone', models.CharField(blank=True, max_length=20, null=True)),
                ('next_num', models.IntegerField(default=1)),
                ('avg_delay', models.FloatField(default=0.0)),
                ('fb_page_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fb_url', models.CharField(default='', max_length=100)),
                ('ig_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('ig_url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=20)),
                ('rep_secret', models.CharField(max_length=20)),
                ('sub_id', models.CharField(max_length=50)),
                ('yay', models.BooleanField(blank=True, null=True)),
                ('quality', models.FloatField(default=0.0)),
                ('cw', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepSecret',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('group', models.CharField(default='unspec', max_length=20)),
                ('first_used', models.DateTimeField(verbose_name='when first used')),
                ('last_used', models.DateTimeField(verbose_name='when last used')),
                ('rep_score', models.FloatField(default=1.0)),
                ('num_subs', models.IntegerField(default=0)),
                ('num_mods', models.IntegerField(default=0)),
                ('acc_yays', models.IntegerField(default=0)),
                ('acc_nays', models.IntegerField(default=0)),
                ('inacc_yays', models.IntegerField(default=0)),
                ('inacc_nays', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fb_id', models.CharField(blank=True, max_length=40, null=True)),
                ('ig_id', models.CharField(blank=True, max_length=40, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(max_length=20)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('rep_secret', models.CharField(blank=True, max_length=30, null=True)),
                ('yays', models.IntegerField(default=0)),
                ('nays', models.IntegerField(default=0)),
                ('quality', models.FloatField(default=0.0)),
                ('cw', models.CharField(default='{}', max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('sub_num', models.CharField(default='N/A', max_length=20)),
                ('num_coms', models.IntegerField(default=0)),
                ('dt_sub', models.DateTimeField(blank=True, null=True, verbose_name='when submitted')),
                ('dt_last_mod', models.DateTimeField(blank=True, null=True, verbose_name='when last modded')),
                ('dt_decided', models.DateTimeField(blank=True, null=True, verbose_name='when fully voted')),
                ('dt_published', models.DateTimeField(blank=True, null=True, verbose_name='when published')),
            ],
        ),
    ]
