# Generated by Django 3.2.9 on 2022-01-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0035_group_moderation_repsecret_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='fb_url',
            field=models.CharField(default='https://facebook.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='ig_url',
            field=models.CharField(default='https://instagram.com', max_length=100),
        ),
    ]
