# Generated by Django 3.2.9 on 2022-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0036_auto_20220122_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num_posts',
            field=models.IntegerField(default=0),
        ),
    ]
