# Generated by Django 3.2.9 on 2022-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0038_submission_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='nays',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='yays',
            field=models.FloatField(default=0.0),
        ),
    ]
