# Generated by Django 3.2.9 on 2022-01-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0039_auto_20220125_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repsecret',
            name='acc_nays',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='repsecret',
            name='acc_yays',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='repsecret',
            name='inacc_nays',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='repsecret',
            name='inacc_yays',
            field=models.FloatField(default=0.0),
        ),
    ]
