# Generated by Django 4.0.4 on 2022-06-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0042_group_color1_group_color2_group_color3_group_color4'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(default='GREEN', max_length=10),
        ),
    ]
