# Generated by Django 4.0.4 on 2022-06-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0043_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
