# Generated by Django 4.0.4 on 2022-10-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secport', '0044_group_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
